stages:
  prepare:
    cmd: python src/00_prepare.py
    deps:
      - src/00_prepare.py
    outs:
      - data
  train:
    cmd: python src/01_train.py
    deps:
      - src/00_prepare.py
    outs:
      - metrics/train
      - model
  evaluate: 
    cmd: python src/02_evaluate.py
    deps:
      - src/02_evaluate.py
    outs:
      - metrics/validation
      - plots
plots:
  - data
