stages:
  prepare:
    cmd: python src/00_prepare.py
    deps:
      - src/00_prepare.py
    outs:
      - data
  train:
    cmd: python src/01_train.py
    deps:
      - src/00_prepare.py
    outs:
      - metrics/train
      - model
  validate: 
    cmd: python src/02_validate.py
    deps:
      - src/00_prepare.py
      - src/01_train.py
    outs:
      - metrics/validation
      - plots
  #evaluate: 
    #cmd: python src/03_evaluate.py
    #deps:
      #- src/02_evaluate.py
    #outs:
      #- metrics/validation
      #- plots
plots:
  - data
