"train_percentage": 0.8
"validation_percentage": 0.1
"test_percentage": 0.1

"hidden_layers": 50
"output_layers": 1

"learning_rate": 0.01
"epochs": 100000

"data_dir": "data/"
"model_dir": "model/"
"train_data_dir": "metrics/train/"
